# GitHub Pages config

title: JSON TypeScript Library
description: TypeScript Library for JSON
author:
  name: © TypeScriptLibs and Contributors
  email: bug@typescriptlibs.org

github:
  private: true

header_pages:
  - www/api.md
  - www/downloads.md
  - SECURITY.md
  - LICENSE.md
  - www/all-libraries.md

include:
  - LICENSE.md
  - README.md
  - SECURITY.md
  - www/all-libraries.md
  - www/api.md
  - www/downloads.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

show_excerpts: false

remote_theme: jekyll/minima@c6e74bb

minima:
  date_format: "%Y-%m-%d"
  skin: auto
  social_links:
    - { platform: github,   user_url: "https://github.com/typescriptlibs/tsl-core-json/" }
    - { platform: mastodon, user_url: "https://mastodon.social/@typescriptlibs" }
    - { platform: rss,      user_url: "feed.xml" }

sass:
  quiet_deps: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
